name: "File"
description: "Files GitHub issues to track potential accessibility gaps."

inputs:
  findings:
    description: "List of potential accessibility gaps, as stringified JSON"
    required: true
  repository:
    description: "Repository (with owner) to file issues in"
    required: true
  token:
    description: "Token with fine-grained permission 'issues: write'"
    required: true
  cached_filings:
    description: "Cached filings from previous runs, as stringified JSON. Without this, duplicate issues may be filed."
    required: false

outputs:
  filings:
    description: "List of issues filed (and their associated finding(s)), as stringified JSON"

runs:
  using: "node24"
  main: "bootstrap.js"

branding:
  icon: "compass"
  color: "blue"
