name: "continuous-accessibility-scanner"
description: "Finds potential accessibility gaps, files GitHub issues to track them, and attempts to fix them with Copilot."

inputs:
  urls:
    description: "Newline-delimited list of URLs to check for accessibility issues"
    required: true
    multiline: true
  repository:
    description: "Repository (with owner) to file issues in"
    required: true
  token:
    description: "Personal access token (PAT) with fine-grained permissions 'issues: write' and 'pull_requests: write'"
    required: true

runs:
  using: "composite"
  steps:
    - name: Find
      id: find
      uses: github/continuous-accessibility-scanner/.github/actions/find@main
      with:
        urls: ${{ inputs.urls }}
    - name: File
      id: file
      uses: github/continuous-accessibility-scanner/.github/actions/file@main
      with:
        findings: ${{ steps.find.outputs.findings }}
        repository: ${{ inputs.repository }}
        token: ${{ inputs.token }}
    - name: Fix
      id: fix
      uses: github/continuous-accessibility-scanner/.github/actions/fix@main
      with:
        issue_numbers: ${{ steps.file.outputs.issue_numbers }}
        repository: ${{ inputs.repository }}
        token: ${{ inputs.token }}

branding:
  icon: "compass"
  color: "blue"