name: "continuous-accessibility-scanner"
description: "Finds potential accessibility gaps, files GitHub issues to track them, and attempts to fix them with Copilot."

inputs:
  urls:
    description: "Newline-delimited list of URLs to check for accessibility issues"
    required: true
    multiline: true
  repository:
    description: "Repository (with owner) to file issues in"
    required: true
  token:
    description: "Personal access token (PAT) with fine-grained permissions 'contents: write', 'issues: write', and 'pull_requests: write'"
    required: true

runs:
  using: "composite"
  steps:
    - name: Restore cached_findings
      id: restore
      uses: github/continuous-accessibility-scanner/.github/actions/gh-cache/cache@smockle/cache-findings
      with:
        key: cached_findings-${{ github.ref_name }}
        token: ${{ inputs.token }}
    - name: Find
      id: find
      uses: github/continuous-accessibility-scanner/.github/actions/find@smockle/cache-findings
      with:
        urls: ${{ inputs.urls }}
    - name: File
      id: file
      uses: github/continuous-accessibility-scanner/.github/actions/file@smockle/cache-findings
      with:
        findings: ${{ steps.find.outputs.findings }}
        repository: ${{ inputs.repository }}
        token: ${{ inputs.token }}
        cached_findings: ${{ steps.restore.outputs.value }}
    - name: Fix
      id: fix
      uses: github/continuous-accessibility-scanner/.github/actions/fix@smockle/cache-findings
      with:
        issue_urls: ${{ steps.file.outputs.opened_issue_urls }}
        repository: ${{ inputs.repository }}
        token: ${{ inputs.token }}
    - name: Save cached_findings
      uses: github/continuous-accessibility-scanner/.github/actions/gh-cache/cache@smockle/cache-findings
      with:
        key: cached_findings-${{ github.ref_name }}
        value: ${{ steps.file.outputs.findings }}
        token: ${{ inputs.token }}

branding:
  icon: "compass"
  color: "blue"