name: "continuous-ai-for-accessibility-scanner"
description: "Finds potential accessibility gaps, files GitHub issues to track them, and attempts to fix them with Copilot."

inputs:
  urls:
    description: "Newline-delimited list of URLs to check for accessibility issues"
    required: true
    multiline: true
  repository:
    description: "Repository (with owner) to file issues in"
    required: true
  token:
    description: "Personal access token (PAT) with fine-grained permissions 'contents: write', 'issues: write', and 'pull_requests: write'"
    required: true
  cache_key:
    description: "Key for caching findings across runs"
    required: true
  login_url:
    description: "If scanned pages require authentication, the URL of the login page"
    required: false
  username:
    description: "If scanned pages require authentication, the username to use for login"
    required: false
  password:
    description: "If scanned pages require authentication, the password to use for login"
    required: false
  auth_context:
    description: "If scanned pages require authentication, a stringified JSON object containing 'username', 'password', 'cookies', and/or 'localStorage' from an authenticated session"
    required: false
  skip_copilot_assignment:
    description: "Whether to skip assigning filed issues to Copilot"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Restore cached results
      id: restore
      uses: ./.github/actions/gh-cache/cache
      with:
        key: ${{ inputs.cache_key }}
        token: ${{ inputs.token }}
    - if: ${{ steps.restore.outputs.value }}
      name: Normalize cache format
      id: normalize_cache
      shell: bash
      run: |
        # Migrate cache format from v1 to v2:
        # If cached data is a list of Finding objects, each with 'issueUrl' keys (i.e. v1),
        # convert to a list of (partial) Result objects, each with 'findings' and 'issue' keys (i.e. v2).
        # Otherwise, re-output as-is.
        echo "value=$(echo '${{ steps.restore.outputs.value }}' | jq 'if (type == "array" and length > 0 and .[0] | has("issueUrl")) then map({findings: [del(.issueUrl)], issue: {url: .issueUrl}}) else . end' )" >> $GITHUB_OUTPUT
    - if: ${{ inputs.login_url && inputs.username && inputs.password && !inputs.auth_context }}
      name: Authenticate
      id: auth
      uses: ./.github/actions/auth
      with:
        login_url: ${{ inputs.login_url }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
    - name: Find
      id: find
      uses: ./.github/actions/find
      with:
        urls: ${{ inputs.urls }}
        auth_context: ${{ inputs.auth_context || steps.auth.outputs.auth_context }}
    - name: File
      id: file
      uses: ./.github/actions/file
      with:
        findings: ${{ steps.find.outputs.findings }}
        repository: ${{ inputs.repository }}
        token: ${{ inputs.token }}
        cached_filings: ${{ steps.normalize_cache.outputs.value }}
    - if: ${{ steps.file.outputs.filings }}
      name: Get issues from filings
      id: get_issues_from_filings
      shell: bash
      run: |
        # Get issues with 'state: open' from Filing objects
        echo "issues=$(echo '${{ steps.file.outputs.filings }}' | jq '[.[] | select(.issue.state == "open") | .issue]')" >> $GITHUB_OUTPUT
    - if: ${{ inputs.skip_copilot_assignment != 'true' }}
      name: Fix
      id: fix
      uses: ./.github/actions/fix
      with:
        issues: ${{ steps.get_issues_from_filings.outputs.issues }}
        repository: ${{ inputs.repository }}
        token: ${{ inputs.token }}
    - name: Save cached results
      uses: ./.github/actions/gh-cache/cache
      with:
        key: ${{ inputs.cache_key }}
        value: ${{ steps.file.outputs.filings }}
        token: ${{ inputs.token }}

branding:
  icon: "compass"
  color: "blue"
