name: "continuous-accessibility-scanner"
description: "Finds potential accessibility gaps, files GitHub issues to track them, and attempts to fix them with Copilot."

inputs:
  urls:
    description: "Newline-delimited list of URLs to check for accessibility issues"
    required: true
    multiline: true
  repository:
    description: "Repository (with owner) to file issues in"
    required: true
  token:
    description: "Personal access token (PAT) with fine-grained permissions 'issues: write' and 'pull_requests: write'"
    required: true

runs:
  using: "node20"
  main: "bootstrap.js"

branding:
  icon: "compass"
  color: "blue"