name: "Find"
description: "Finds potential accessibility gaps."

inputs:
  urls:
    description: "Newline-delimited list of URLs to check for accessibility issues"
    required: true
    multiline: true
  auth_context:
    description: "Stringified JSON object containing 'username', 'password', 'cookies', and/or 'localStorage' from an authenticated session"
    required: false

outputs:
  findings:
    description: "List of potential accessibility gaps, as stringified JSON"

  wait_for_selector:
    description: "A CSS selector for an element to wait for before scanning the page"
    required: false
  wait_for_timeout:
    description: "The maximum time in milliseconds to wait for the selector"
    required: false
    default: "30000"
  device:
    description: "The device to emulate from the list of Playwright-supported devices"
    required: false

runs:
  using: "node24"
  main: "bootstrap.js"

branding:
  icon: "compass"
  color: "blue"
