name: "save"
description: "Commit a file or directory to an orphaned 'gh-cache' branch"

inputs:
  path:
    description: "Relative path to a file or directory to save"
    required: true
  token:
    description: "Token with fine-grained permissions 'contents: write'"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout repository to temporary directory
      uses: actions/checkout@v4
      with:
        token: ${{ inputs.token }}
        fetch-depth: 0
        path: .gh-cache-${{ github.run_id }}

    - name: Switch to gh-cache branch (or create orphan)
      shell: bash
      working-directory: .gh-cache-${{ github.run_id }}
      run: |
        if git ls-remote --exit-code --heads origin gh-cache >/dev/null; then
          git checkout gh-cache
        else
          git checkout --orphan gh-cache
          git rm -rf . # Clear files from the initial checkout, to avoid adding them to the orphaned branch
        fi

    - name: Copy file to repo
      shell: bash
      run: |
        cp -Rf "${{ inputs.path }}" ".gh-cache-${{ github.run_id }}/${{ inputs.path }}"

    - name: Commit and push
      shell: bash
      working-directory: .gh-cache-${{ github.run_id }}
      run: |
        git add "${{ inputs.path }}"
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git commit -m "$(printf 'Save artifact: %s' "${{ inputs.path }}")" || echo "No changes to commit"
        git push origin gh-cache

    - name: Clean up temporary directory
      shell: bash
      run: |
        rm -rf .gh-cache-${{ github.run_id }}

branding:
  icon: "upload"
  color: "blue"
