name: "save"
description: "Commit a file or directory to an orphaned 'gh-cache' branch"

inputs:
  path:
    description: "Relative path to a file or directory to save"
    required: true
  token:
    description: "Token with fine-grained permissions 'contents: write'"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout repository to temporary directory
      uses: actions/checkout@v4
      with:
        token: ${{ inputs.token }}
        fetch-depth: 0
        path: .gh-cache-${{ github.run_id }}
        show-progress: 'false'

    - name: Switch to gh-cache branch (or create orphan)
      shell: bash
      working-directory: .gh-cache-${{ github.run_id }}
      run: |
        if git ls-remote --exit-code --heads origin gh-cache >/dev/null; then
          git checkout gh-cache >/dev/null 2>&1
          echo "Checked out existing 'gh-cache' branch"
        else
          git checkout --orphan gh-cache >/dev/null 2>&1
          git rm -rfq . # Clear files from the initial checkout, to avoid adding them to the orphaned branch
          echo "Created new orphaned 'gh-cache' branch"
        fi

    - name: Copy file to repo
      shell: bash
      run: |
        if [ -f "${{ inputs.path }}" ]; then
          cp -Rf "${{ inputs.path }}" ".gh-cache-${{ github.run_id }}/${{ inputs.path }}"
          echo "Copied '${{ inputs.path }}' to 'gh-cache' branch"
        fi

    - name: Commit and push
      shell: bash
      working-directory: .gh-cache-${{ github.run_id }}
      run: |
        if [ -f "${{ inputs.path }}" ]; then
          git add "${{ inputs.path }}"
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git commit -m "$(printf 'Save artifact: %s' "${{ inputs.path }}")" \
            && echo "Committed '${{ inputs.path }}' to 'gh-cache' branch" \
            || echo "No changes to commit"
          git push origin gh-cache
        else
          echo "'${{ inputs.path }}' does not exist"
          echo "Skipping commit and push"
        fi

    - name: Clean up temporary directory
      shell: bash
      run: |
        rm -rf .gh-cache-${{ github.run_id }}

branding:
  icon: "upload"
  color: "blue"
